on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: jekyll/jekyll
      volumes:
        - $PWD:/srv/jekyll
    steps:
     - name: Checkout
       uses: actions/checkout@v3
       with:
        fetch-depth: 0
        
     - name: Generate
       run:  jekyll build