on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: jekyll/jekyll
    steps:
     - name: Checkout
       uses: actions/checkout@v4
        
     - name: Generate
       run:  |
        chmod 777 -R src
        cd src
        jekyll build