on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: jekyll/jekyll
    steps:
     - name: Workdirectory
       run: cd /srv/jekyll
       
     - name: Checkout
       uses: actions/checkout@v3
       with:
        fetch-depth: 0
        
     - name: Generate
       run:  |
        cd src
        jekyll build