on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    container: 
      image: jekyll/jekyll
    steps:
     - name: Checkout
       uses: actions/checkout@v4
        
     - name: Generate
       run:  |
        chmod 777 -R src
        cd src
        jekyll build

     - name: publish
       uses: genietim/ftp-action@releases/v4
       with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: "src/_site"
        remoteDir: "/"