on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: jekyll/jekyll
    defaults:
      run:
        shell: bash
        working-directory: /srv/jekyll
    steps:
     - name: Checkout
       uses: actions/checkout@v3
       with:
        fetch-depth: 0
        
     - name: Generate
       run:  |
        ls
        echo "$PWD"
        mkdir piet
        ls
        cd src
        jekyll build