on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: jekyll/jekyll
    defaults:
      run:
        shell: bash
        working-directory: /srv/jekyll
    steps:
     - name: Checkout
       uses: actions/checkout@v4
        
     - name: Generate
       run:  |
        cp $GITHUB_WORKSPACE /srv/jekyll
        ls
        echo "$PWD"
        mkdir piet
        ls
        cd src
        jekyll build